Private-events
Temmarie/private-events-brite pull request #1
Opened 2020-07-15 19:57 UTC by kotoku-code

In this project, we built a site similar to a private Eventbrite which allows users to create events and then manage user signups. Users can create events and send invitations and parties. Events take place at a specific date.

Thank you for reviewing our project. if you have any suggested changes, we look forward to your feedback.

kind regards Kotoku & Temmarie

2020-07-16 07:36 UTC, uche-inyama requested changes
## Changes Required

Hi team :wave: 

So far, so good, you have made some progress :clap: :clap: 

However, there are features you missed to implement.

- [x] Event's index page should display past and upcoming events lists ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/past_upcoming_events_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))

- [x] The user's show page should display events the user has created and events that the user is attending to be separated in past and upcoming ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/user_events_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))

- [x] There should be navigation links present at the top of the page ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/navigation_links_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations)) In a nutshell, make your UI look better, there should be a navigation bar in your application.

- [x] Your commit messages are not descriptive.

- [x] There are logic in your view files. That is, conditional statements. View-related logic can be put in View helpers (app/helpers/\*_helper.rb)

After making these required changes, submit another for a code review.

Kindly reach out, if you need clarifications on slack @ Inyama, Uchechukwu Henry.

#### ``` Have a great day ``` :slightly_smiling_face: 

**``` Uchechukwu Henry Inyama ```**

2020-07-16 22:28 UTC, mosesogwo requested changes
**Hello! :clap: Good progress :+1: But somethings are still missing:**

:point_right: As indicated in the last review, the user show page will have 3 categories: Events he created, events he is attending (upcoming) and events he has attended (past). Yours is missing events he created.

:point_right: Remove commented code in user show page or uncomment it if it is needed.

:point_right: Extract conditional logic in user show page and event show page and in any other views into helper methods.

:point_right: In your event create action, use `current_user.events.build` instead of `Event.new`

:point_right: Write tests for event management feature.
 
**Optional:** indent your view files properly.

_**Kindly make these changes and submit another code review request.**_

**Any questions? You can reach me on Slack (Moses Ogwo)**

**Cheers:stars:**

### Status: Changes Requested.

2020-07-16 22:28 UTC, mosesogwo commented on app/views/events/index.html.erb
> +<% @events.upcoming.each do |event|%>
This could be resolved in the controller and the variable @upcoming_events passed to the view.

2020-07-16 22:28 UTC, mosesogwo commented on app/views/events/index.html.erb
> +<% @events.past.each do |event|%>
This could be resolved in the controller and the variable @past_events passed to the view.

2020-07-17 23:34 UTC, rOluochKe approved these changes
Hello Team!
### Well done guys :clap: You got it right this time. The project has been approved. Congratulations :boom: :100:
### Merge and submit the project. Good luck with the next one.
- Happy coding!

2020-07-19 11:36 UTC, merged